name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: |
          yarn

      - name: Run ESLint and Prettier
        run: |
          yarn lint
          yarn prettier

      - name: Build @persona-js/verify
        run: |
          yarn workspace @persona-js/verify build
